### ISSUE TITLE
bug: Centre landing page contents

### ISSUE THREAD

**Issue by JessicaF** [csesoc/Freerooms#431]
Contents on the landing page are not centred properly, see screenshot below for mobile view:

![Image](https://github.com/devsoc-unsw/freerooms/assets/54833118/7ad36b3d-9500-4aff-b411-4055e3545aeb)

**Comment by JessicaF** [comment]
Issue is with DevTools only and cannot be replicated on mobile

**Comment by azjy89** [comment]
The landing page is centered when using any Dimensions except for Dimensions: Responsive. It seems to be an issue with chrome devtools.
